### PR TITLE
Define ShortClassNameSnakeCase TypeTags

### PR DESCRIPTION
**Pull request by GeluOltean**
Changes related to https://github.com/julienrf/play-json-derived-codecs/issues/88

### CODE REVIEW

**Comment by julienrf** [comment]
To be honest, I don’t know what’s the problem. It might be a limitation of the shapeless machinery… I noticed that the error disappears if we don’t write a recursive type (ie, if we change `BarFoo` to not include a `CompositeNameClass`).

**Comment by GeluOltean** [comment]
Oh, I hadn't noticed that! I'll rewrite around it, unfortunately I am not familiar enough with shapeless to be able to identity the issue. Will update the PR with working tests by tomorrow, at the latest. Thanks!

**Comment by GeluOltean** [comment]
Hey @julienrf , sorry for the delay. Pushed the test now. Let me know what you think.

**Review by julienrf — APPROVED** [review]

**Comment by julienrf** [comment]
This is available in release 10.1.0. Thank you @GeluOltean!

**Pull request merged**
