### PR TITLE
Update play-json dependency to 3.x, update README. Fixes #91

### LINKED ISSUE #91: Support for play-json 3.x
The play-json team changed the groupId for the dependency from `org.typesafe.play` to `org.playframework` for 3.x and later (https://github.com/playframework/play-json/releases/tag/3.0.0).

As a workaround, it still uses the same package names so this library can be used by including the dependency directly and adding an exclusion rule, e.g.

```scala
libraryDependencies ++= Seq(
  "org.playframework" %% "play-json" % "3.0.1",
  "org.julienrf" %% "play-json-derived-codecs" % "10.1.0"
)

excludeDependencies ++= Seq(
  // As of Play 3.0, groupId has changed to org.playframework; exclude transitive dependencies to the old artifacts
  ExclusionRule(organization = "com.typesafe.play")
)
```

It may be worth marking the dependency as `Optional` in the library, to avoid pulling in incompatible play-json dependencies as various libraries update to support 3.x

### PR DESCRIPTION
**Pull request by matmannion**
Adds support for play-json 3.0 with the new groupId on the dependency.

Fixes #91

### CODE REVIEW

**Review by julienrf — APPROVED** [review]

**Comment by julienrf** [comment]
Thank you for the quick PR!

You will also have to reset the compatibility intention to `Compatibility.None`:

https://github.com/julienrf/play-json-derived-codecs/blob/214b5a19a61ae2ba9a50c76dd093f014ec961709/build.sbt#L10

And it seems we need to update our Scala.js dependency as well because play-json is using a very recent version of Scala.js.

**Comment by Dichotomia** [comment]
Hello. Any chance to see this merged?

**Comment by sdudzin** [comment]
@julienrf any chance of merging this in the nearest future?

**Comment by julienrf** [comment]
Hello! Thank you for your interest. Can someone fix the CI failure according to the explanation at https://github.com/julienrf/play-json-derived-codecs/pull/92#issuecomment-1803870815?

**Pull request merged**
